[package]
name = "shared-configuration"
description = "Chain shared configuration Polimec"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec.workspace = true

# FRAME
frame-system.workspace = true
frame-support.workspace = true
sp-arithmetic.workspace = true
parachains-common.workspace = true
sp-std.workspace = true

[features]
default = [ "std" ]
fast-gov = []
std = [
	"frame-support/std",
	"parachains-common/std",
	"sp-arithmetic/std",
	"sp-std/std",
]
runtime-benchmarks = [ "frame-support/runtime-benchmarks" ]
