[package]
name = "shared-configuration"
description = "Chain shared configuration Polimec"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec.workspace = true
parity-scale-codec = { version = "3.6.5", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.9.0", default-features = false, features = [
	"derive",
] }

# FRAME
frame-system.workspace = true
frame-support.workspace = true
sp-arithmetic.workspace = true
parachains-common.workspace = true
sp-std.workspace = true
pallet-funding.workspace = true
orml-traits.workspace = true
pallet-transaction-payment.workspace = true
pallet-balances.workspace = true
pallet-authorship.workspace = true

[features]
default = [ "std" ]
fast-gov = []
std = [
	"frame-support/std",
	"frame-system/std",
	"orml-traits/std",
	"pallet-funding/std",
	"parachains-common/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-arithmetic/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-funding/runtime-benchmarks",
]
testing-node = [ "pallet-funding/testing-node" ]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-funding/try-runtime",
]
