[workspace]
members = [
    "node",
    "pallets/multi-mint",
    "pallets/traits",
    "pallets/proposal",
    "pallets/multi-stake",
    "pallets/bonding-payouts",
    "pallets/issuer-council",
    "runtime",
]
[profile.release]
panic = "unwind"
