# Basic
hard_tabs = true
max_width = 120
use_small_heuristics = "Max"
# Imports
imports_granularity = "Crate"
reorder_imports = true
# Consistency
newline_style = "Unix"
# Misc
spaces_around_ranges = false
binop_separator = "Back"
reorder_impl_items = true
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_semicolon = false
use_field_init_shorthand = true
edition = "2021"