
//! Autogenerated weights for `pallet_funding`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-03-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pop-os`, CPU: `13th Gen Intel(R) Core(TM) i9-13900K`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/polimec-standalone-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_funding
// --extrinsic
// *
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=runtimes/testnet/src/weights/pallet_funding.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_funding`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_funding::WeightInfo for WeightInfo<T> {
	/// Storage: PolimecFunding Images (r:0 w:1)
	/// Proof Skipped: PolimecFunding Images (max_values: None, max_size: None, mode: Measured)
	fn note_image() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_675 nanoseconds.
		Weight::from_ref_time(5_945_000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PolimecFunding Images (r:1 w:0)
	/// Proof Skipped: PolimecFunding Images (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding NextProjectId (r:1 w:1)
	/// Proof Skipped: PolimecFunding NextProjectId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: PolimecFunding Projects (r:0 w:1)
	/// Proof Skipped: PolimecFunding Projects (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsInfo (r:0 w:1)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsIssuers (r:0 w:1)
	/// Proof Skipped: PolimecFunding ProjectsIssuers (max_values: None, max_size: None, mode: Measured)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `111`
		//  Estimated: `3525`
		// Minimum execution time: 12_383 nanoseconds.
		Weight::from_parts(12_884_000, 3525)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: PolimecFunding ProjectsIssuers (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsIssuers (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsInfo (r:1 w:1)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsActive (r:1 w:1)
	/// Proof Skipped: PolimecFunding ProjectsActive (max_values: Some(1), max_size: None, mode: Measured)
	fn start_evaluation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `207`
		//  Estimated: `6066`
		// Minimum execution time: 11_756 nanoseconds.
		Weight::from_parts(12_260_000, 6066)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PolimecFunding ProjectsIssuers (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsIssuers (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsInfo (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: PolimecFunding Bonds (r:1 w:1)
	/// Proof Skipped: PolimecFunding Bonds (max_values: None, max_size: None, mode: Measured)
	/// Storage: Balances Locks (r:1 w:1)
	/// Proof: Balances Locks (max_values: None, max_size: Some(1299), added: 3774, mode: MaxEncodedLen)
	fn bond() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `370`
		//  Estimated: `14912`
		// Minimum execution time: 18_423 nanoseconds.
		Weight::from_parts(18_951_000, 14912)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: PolimecFunding ProjectsIssuers (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsIssuers (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding Images (r:1 w:0)
	/// Proof Skipped: PolimecFunding Images (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsInfo (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding Projects (r:1 w:1)
	/// Proof Skipped: PolimecFunding Projects (max_values: None, max_size: None, mode: Measured)
	fn edit_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `11716`
		// Minimum execution time: 13_968 nanoseconds.
		Weight::from_parts(14_383_000, 11716)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PolimecFunding ProjectsIssuers (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsIssuers (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsInfo (r:1 w:1)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	fn start_auction() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `268`
		//  Estimated: `5486`
		// Minimum execution time: 13_169 nanoseconds.
		Weight::from_parts(13_615_000, 5486)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: PolimecFunding ProjectsIssuers (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsIssuers (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsInfo (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding Projects (r:1 w:0)
	/// Proof Skipped: PolimecFunding Projects (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding AuctionsInfo (r:1 w:1)
	/// Proof Skipped: PolimecFunding AuctionsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `633`
		//  Estimated: `15035`
		// Minimum execution time: 23_977 nanoseconds.
		Weight::from_parts(24_786_000, 15035)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: PolimecFunding ProjectsIssuers (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsIssuers (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsInfo (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: PolimecFunding Contributions (r:1 w:1)
	/// Proof Skipped: PolimecFunding Contributions (max_values: None, max_size: None, mode: Measured)
	fn contribute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `474`
		//  Estimated: `14053`
		// Minimum execution time: 28_993 nanoseconds.
		Weight::from_parts(29_816_000, 14053)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: PolimecFunding ProjectsInfo (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding Contributions (r:1 w:1)
	/// Proof Skipped: PolimecFunding Contributions (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_contribution_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `877`
		//  Estimated: `14569`
		// Minimum execution time: 25_594 nanoseconds.
		Weight::from_parts(26_497_000, 14569)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: PolimecFunding ProjectsActive (r:1 w:0)
	/// Proof Skipped: PolimecFunding ProjectsActive (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: PolimecFunding ProjectsInfo (r:100 w:100)
	/// Proof Skipped: PolimecFunding ProjectsInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: PolimecFunding Bonds (r:200 w:0)
	/// Proof Skipped: PolimecFunding Bonds (max_values: None, max_size: None, mode: Measured)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `15727`
		//  Estimated: `790176`
		// Minimum execution time: 1_236_894 nanoseconds.
		Weight::from_parts(1_252_379_000, 790176)
			.saturating_add(T::DbWeight::get().reads(301))
			.saturating_add(T::DbWeight::get().writes(100))
	}
}
