[package]
name = 'pallet-funding'
description = 'FRAME pallet handle funding'
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
parity-scale-codec = { workspace = true, features = [
	"derive",
] }
scale-info = { workspace = true, features = ["derive"] }

# Substrate dependencies
frame-support.workspace = true
frame-system.workspace = true
sp-std.workspace = true
sp-runtime.workspace = true
sp-arithmetic.workspace = true
polimec-traits.workspace = true

# Benchmarking dependencies
frame-benchmarking = { workspace = true, optional = true }

[dev-dependencies]
sp-core.workspace = true
sp-io.workspace = true
pallet-balances.workspace = true
pallet-insecure-randomness-collective-flip.workspace = true
pallet-assets.workspace = true
pallet-credentials.workspace = true

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-arithmetic/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-credentials/std",
	"polimec-traits/std",
	"frame-benchmarking?/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
