[package]
name = 'pallet-funding'
authors = ['Polimec Foundation <info@polimec.org>']
documentation = "https://wiki.polimec.org/"
edition = "2021"
homepage = "https://www.polimec.org/"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Polimec/polimec-node"
version = "0.1.0"
rust-version = "1.69.0"

[dependencies]
serde = { version = "*", optional = true }
parity-scale-codec = { version = "3.0.0", features = [
    "derive",
], default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = [
    "derive",
] }
itertools = { version = "0.11.0", default-features = false }

# Substrate dependencies
frame-benchmarking = {workspace = true, optional = true}
frame-support.workspace = true
frame-system.workspace = true
sp-std.workspace = true
sp-runtime.workspace = true
sp-arithmetic.workspace = true
polimec-traits.workspace = true

[dev-dependencies]
sp-core.workspace = true
sp-io.workspace = true
pallet-balances.workspace = true
pallet-insecure-randomness-collective-flip.workspace = true
pallet-assets.workspace = true
pallet-linear-release.workspace = true

[features]
default = ["std"]
std = [
    "itertools/use_std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-arithmetic/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-assets/std",
    "pallet-balances/std",
    "polimec-traits/std",
    "pallet-linear-release/std",
    "frame-benchmarking?/std",
    "serde",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "pallet-assets/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
