[package]
name = 'pallet-credentials-api'
description = 'FRAME pallet handle credentials'
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = [
  "derive",
] }

jsonrpsee = { workspace = true, features = ["server", "macros"] }

sp-api.workspace = true
sp-blockchain.workspace = true
sp-runtime.workspace = true
polimec-traits.workspace = true
polimec-runtime-api-credentials.workspace = true

[features]
default = ["std"]
std = [
  "sp-api/std",
  "sp-runtime/std",
  "polimec-runtime-api-credentials/std",
  "polimec-traits/std",
]
