[package]
name = 'polimec-runtime-api-credentials'
description = "Runtime APIs for dealing with credentials and membership."
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
parity-scale-codec = {  workspace = true, features = [
	"derive",
] }
scale-info = { workspace = true, features = ["derive"] }

sp-runtime.workspace = true
sp-api.workspace = true
sp-std.workspace = true
polimec-traits.workspace = true


[features]
default = ["std"]
std = [
	"sp-api/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-runtime/std",
	"polimec-traits/std",
]
