[package]
name = 'pallet-credentials-runtime-api'
version = "0.1.0"
authors = ['Polimec Team <https://github.com/Polimec>']
edition = "2021"
license = "Unlicense"
publish = false
repository = 'https://github.com/polimec/polimec-node'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }

sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32", default-features = false }
sp-std  = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32", default-features = false }
polimec-traits = { path = "../../../../traits", default-features = false }




[features]
default = ["std"]
std = [
	"sp-api/std",
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-runtime/std",
	"polimec-traits/std",
]
