[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

	[[relaychain.nodes]]
	name = "charlie"

	[[relaychain.nodes]]
	name = "dave"

[[parachains]]
id = 2000
genesis_state_path = "./scripts/zombienet/native/genesis/para-2000-state"
genesis_wasm_path = "./scripts/zombienet/native/genesis/para-2000-wasm"

	[[parachains.collators]]
	name = "polimec-collator-1"
	command = "polimec-node"

	[[parachains.collators]]
	name = "polimec-collator-2"
	command = "polimec-node"
