[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

	[[relaychain.nodes]]
	name = "charlie"

	[[relaychain.nodes]]
	name = "dave"

[[parachains]]
id = 2000
genesis_state_path = "./genesis/palceholder-base-state"
genesis_wasm_path = "./genesis/palceholder-base-wasm"

	[[parachains.collators]]
	name = "polimec-collator"
	command = "polimec"