[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

	[[relaychain.nodes]]
	name = "charlie"

	[[relaychain.nodes]]
	name = "dave"

[[parachains]]
id = 2000
chain = "base-polkadot"

	[[parachains.collators]]
	name = "collator1"
	command = "polimec-parachain-node"

	[[parachains.collators]]
	name = "collator2"
	command = "polimec-parachain-node"
