[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "../polkadot/target/release/polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

	[[relaychain.nodes]]
	name = "charlie"

	[[relaychain.nodes]]
	name = "dave"

[[parachains]]
id = 2000
chain = "base-polkadot"

	[[parachains.collators]]
	name = "collator1"
	command = "./target/release/polimec-parachain-node"

	[[parachains.collators]]
	name = "collator2"
	command = "./target/release/polimec-parachain-node"
