[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "eve"

	[[relaychain.nodes]]
	name = "ferdie"

	[[relaychain.nodes]]
	name = "charlie"

	[[relaychain.nodes]]
	name = "dave"

[[parachains]]
id = 2000
chain = "base-rococo-local"

	[[parachains.collators]]
	name = "alice"
	command = "./target/release/polimec-parachain-node"

	[[parachains.collators]]
	name = "bob"
	command = "./target/release/polimec-parachain-node"
