[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

[[parachains]]
id = 2000
genesis_state_path = "./scripts/zombienet/native/genesis/base-state-rococo-local"
genesis_wasm_path = "./scripts/zombienet/native/genesis/base-wasm-rococo-local"

	[[parachains.collators]]
	name = "polimec-collator"
	command = "polimec"
