[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "./polkadot/target/release/polkadot"
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"

    [[relaychain.nodes]]
    name = "bob"

    [[relaychain.nodes]]
    name = "charlie"

    [[relaychain.nodes]]
    name = "dave"

    [[relaychain.nodes]]
    name = "eve"

    [[relaychain.nodes]]
    name = "ferdie"

[[parachains]]
id = 1000
chain = "statemint-local"

	[[parachains.collators]]
	name = "statemint-dev"
	command = "./cumulus/target/release/polkadot-parachain"

[[parachains]]
id = 2000
chain = "dev"
	[[parachains.collators]]
	name = "polimec-collator"
	command = "./polimec/target/release/polimec-parachain-node"

[[parachains]]
id = 3000
chain = "dev"
	[[parachains.collators]]
	name = "penpal-collator"
	command = "./penpal-custom-main/target/release/parachain-template-node"


[[hrmp_channels]]
sender = 1000
recipient = 2000
max_capacity = 8
max_message_size = 8000

[[hrmp_channels]]
sender = 2000
recipient = 1000
max_capacity = 8
max_message_size = 8000

[[hrmp_channels]]
sender = 1000
recipient = 3000
max_capacity = 8
max_message_size = 8000

[[hrmp_channels]]
sender = 3000
recipient = 1000
max_capacity = 8
max_message_size = 8000

[[hrmp_channels]]
sender = 2000
recipient = 3000
max_capacity = 8
max_message_size = 8000

[[hrmp_channels]]
sender = 3000
recipient = 2000
max_capacity = 8
max_message_size = 8000