[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "/usr/local/bin/polkadot"
chain = "rococo-local"


    [[relaychain.nodes]]
    name = "alice"
    ws_port = 6969
    args = ["-lerror", "-lxcm::process_instruction=trace", "-lxcm::execute_xcm_in_credit=trace", "-lxcm::barriers=trace", "-lpallet_funding::hrmp=trace", "-lpallet_funding::test=trace", "--execution=native", ]
    [[relaychain.nodes]]
    name = "bob"

    [[relaychain.nodes]]
    name = "charlie"

    [[relaychain.nodes]]
    name = "dave"

    [[relaychain.nodes]]
    name = "eve"

    [[relaychain.nodes]]
    name = "ferdie"

[[parachains]]
id = 1000
chain = "asset-hub-rococo-dev"

	[[parachains.collators]]
	name = "statemint-dev"
	command = "../polkadot-sdk/target/release/polkadot-parachain"
    args = ["-lerror", "-lxcm::process_instruction=trace", "-lxcm::execute_xcm_in_credit=trace", "-lxcm::barriers=trace", "-lpallet_funding::hrmp=trace", "-lpallet_funding::test=trace", "--execution=native", ]
    ws_port = 7777


[[parachains]]
id = 3344
chain = "politest-populated"
	[[parachains.collators]]
	name = "polimec-testing"
	command = "./target/release/polimec-node"
    args = ["-lerror", "-lxcm::process_instruction=trace", "-lxcm::execute_xcm_in_credit=trace", "-lxcm::barriers=trace", "-lpallet_funding::hrmp=trace", "-lpallet_funding::test=trace", "--execution=native", ]   
    ws_port = 8888

[[parachains]]
id = 3000
chain = "penpal-rococo-3000"
	[[parachains.collators]]
	name = "penpal-collator"
	command = "../polkadot-sdk/target/release/polkadot-parachain"
    args = ["-lerror", "-lxcm::process_instruction=trace", "-lxcm::execute_xcm_in_credit=trace", "-lxcm::barriers=trace", "-lpallet_funding::hrmp=trace", "-lpallet_funding::test=trace", "--execution=native", ]
    ws_port = 9999