[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"


[[parachains]]
id = 1000
chain = "statemine-local"

    [[parachains.collators]]
    name = "statemine-collator"
    command = "polkadot-parachain"

[[parachains]]
id = 2000

	[[parachains.collators]]
	name = "collator1"
	command = "polimec"

