[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "eve"

    [[relaychain.nodes]]
    name = "ferdie"


[[parachains]]
id = 3344

	[[parachains.collators]]
	name = "alice"
	command = "./target/release/polimec-parachain-node"
