[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "./bin/polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

	[[relaychain.nodes]]
	name = "charlie"

	[[relaychain.nodes]]
	name = "dave"

[[parachains]]
id = 2000
chain = "polimec-rococo-local"

	[[parachains.collators]]
	name = "collator1"
	command = "./bin/polimec-parachain-node"
	args = ["--offchain-worker when-authority"]

	[[parachains.collators]]
	name = "collator2"
	command = "./bin/polimec-parachain-node"
	args = ["--offchain-worker when-authority"]