[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "../polkadot/target/release/polkadot"
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"

    [[relaychain.nodes]]
    name = "bob"

    [[relaychain.nodes]]
    name = "charlie"

    [[relaychain.nodes]]
    name = "dave"

    [[relaychain.nodes]]
    name = "eve"

    [[relaychain.nodes]]
    name = "ferdie"


[[parachains]]
id = 2000

	[[parachains.collators]]
	name = "polimec-collator"
	command = "./target/release/polimec-node"

[[parachains]]
id = 3000

	[[parachains.collators]]
	name = "penpal-collator"
	command = "../cumulus/target/release/polkadot-parachain"
    chain = "penpal-polkadot-3000"