[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

	[[relaychain.nodes]]
	name = "charlie"

	[[relaychain.nodes]]
	name = "dave"
