# all options https://taplo.tamasfe.dev/configuration/formatter-options.html

exclude = ["target/**"]

# global rules
[formatting]
reorder_arrays = true
inline_table_expand = false
array_auto_expand = false
array_auto_collapse = false
indent_string = "	"         # tab
