[relaychain]
default_command = "polkadot"
default_args = ["-lparachain=debug"]
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

[[parachains]]
id = 2000
cumulus_based = true
chain = "polimec-polkadot-local"

	[parachains.collator]
	name = "collator1"
	command = "polimec"