[relaychain]
default_command = "polkadot"
default_args = ["-lparachain=debug"]
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"
    args = [ "--alice" ]
	validator = true

	[[relaychain.nodes]]
	name = "bob"
    args = [ "--bob" ]
	validator = true

	[[relaychain.nodes]]
	name = "charlie"
    args = [ "--charlie" ]
	validator = true

	[[relaychain.nodes]]
	name = "dave"
    args = [ "--dave" ]
	validator = true


[[parachains]]
id = 1000
cumulus_based = true

	[[parachains.collators]]
	name = "collator1"
	command = "polimec"
	args = [ "--alice" ]

[[parachains]]
id = 1001
cumulus_based = true

	[[parachains.collators]]
	name = "collator2"
	command = "polimec2001"
	args = [ "--bob" ]

[[hrmpChannels]]
sender = 1000
recipient = 1001
maxCapacity = 8
maxMessageSize = 8192

[[hrmpChannels]]
sender = 1001
recipient = 1000
maxCapacity = 8
maxMessageSize = 8192