//! Autogenerated weights for issuer_council
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 2.0.0
//! DATE: 2020-12-07, STEPS: [10, ], REPEAT: 4, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 128

// Executed Command:
// /home/willi/polimec/polimec-node/target/release/node-polimec
// benchmark
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// -e
// *
// -p
// issuer_council
// -s
// 10
// -r
// 4
// --output
// ../pallets/issuer-council/src/default_weights.rs
// --template
// ../.maintain/weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for issuer_council.
pub trait WeightInfo {
	fn apply_for_seat(p: u32) -> Weight;
	fn exit_council(m: u32) -> Weight;
	fn expel_member(m: u32) -> Weight;
	fn admit_new_member(m: u32) -> Weight;
	fn submit_proposal(m: u32, p: u32) -> Weight;
	fn slash_keep_member(m: u32) -> Weight;
	fn slash_drop_member(m: u32) -> Weight;
	fn vote() -> Weight;
}

// Default weights for this pallet, if not used in a different runtime
impl WeightInfo for () {
	fn apply_for_seat(p: u32) -> Weight {
		(132_786_000 as Weight)
			.saturating_add((831_000 as Weight).saturating_mul(p as Weight))
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
	fn exit_council(m: u32) -> Weight {
		(36_715_000 as Weight)
			.saturating_add((402_000 as Weight).saturating_mul(m as Weight))
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	fn expel_member(m: u32) -> Weight {
		(36_981_000 as Weight)
			.saturating_add((388_000 as Weight).saturating_mul(m as Weight))
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	fn admit_new_member(m: u32) -> Weight {
		(109_595_000 as Weight)
			.saturating_add((555_000 as Weight).saturating_mul(m as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	fn submit_proposal(m: u32, p: u32) -> Weight {
		(74_661_000 as Weight)
			.saturating_add((850_000 as Weight).saturating_mul(m as Weight))
			.saturating_add((1_056_000 as Weight).saturating_mul(p as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	fn slash_keep_member(m: u32) -> Weight {
		(32_151_000 as Weight)
			.saturating_add((635_000 as Weight).saturating_mul(m as Weight))
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	fn slash_drop_member(m: u32) -> Weight {
		(47_636_000 as Weight)
			.saturating_add((653_000 as Weight).saturating_mul(m as Weight))
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	fn vote() -> Weight {
		(93_446_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
}
