[settings]
timeout = 1000
provider = "native"

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"

	[[relaychain.nodes]]
	name = "bob"

	[[relaychain.nodes]]
	name = "charlie"

	[[relaychain.nodes]]
	name = "dave"

[[parachains]]
id = 2000

	[[parachains.collators]]
	name = "collator1"
	command = "./target/release/parachain-template-node"

	[[parachains.collators]]
	name = "collator2"
	command = "./target/release/parachain-template-node"
