[package]
name = "xcm-simulator-example"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Examples of xcm-simulator usage."
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = [
	"derive",
] }
scale-info = { workspace = true, features = ["derive"] }

frame-system.workspace = true
frame-support.workspace = true
pallet-balances.workspace = true
sp-std.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-io.workspace = true

xcm.workspace = true
xcm-emulator.workspace = true
xcm-executor.workspace = true
xcm-builder.workspace = true
pallet-xcm.workspace = true
polkadot-core-primitives.workspace = true
polkadot-runtime-parachains.workspace = true
polkadot-parachain.workspace = true


parachain-info.workspace = true

# Runtimes
polkadot-runtime = true
statemint-runtime.workspace = true
polimec-parachain-runtime.workspace = true
penpal-runtime.workspace = true

[features]
runtime-benchmarks = [
	"statemint-runtime/runtime-benchmarks",
]
