[package]
name = "integration-tests"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[build-dependencies]
substrate-wasm-builder.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = [
    "derive",
] }
scale-info = { workspace = true, features = ["derive"] }

frame-system.workspace = true
frame-support.workspace = true
pallet-balances.workspace = true
sp-std.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-io.workspace = true

xcm.workspace = true
xcm-emulator.workspace = true
xcm-executor.workspace = true
xcm-builder.workspace = true
pallet-xcm.workspace = true
pallet-assets.workspace = true
polkadot-core-primitives.workspace = true
polkadot-runtime-parachains.workspace = true
polkadot-parachain.workspace = true

cumulus-primitives-core.workspace = true
cumulus-pallet-xcm.workspace = true

parachain-info.workspace = true

# Runtimes
polkadot-runtime.workspace = true
statemint-runtime.workspace = true
polimec-parachain-runtime.workspace = true
penpal-runtime.workspace = true
dip-provider-runtime-template = { workspace = true, features = ["std"] }


[features]
default = ["std"]

std = [
    "pallet-assets/std",
    "frame-system/std",
    "frame-support/std",
    "pallet-balances/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-runtime/std",
    "sp-io/std",
    "xcm/std",
    "xcm-builder/std",
    "xcm-executor/std",
    "pallet-xcm/std",
    "polkadot-core-primitives/std",
    "polkadot-runtime-parachains/std",
    "polkadot-parachain/std",
    "parachain-info/std",
    "polkadot-runtime/std",
    "statemint-runtime/std",
    "polimec-parachain-runtime/std",
    "penpal-runtime/std"
]

runtime-benchmarks = [
    "statemint-runtime/runtime-benchmarks",
]
