[package]
name = "integration-tests"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true

readme.workspace = true
repository.workspace = true
version.workspace = true

[build-dependencies]
substrate-wasm-builder.workspace = true

[dependencies]
parity-scale-codec = {  workspace = true, features = [
    "derive",
] }
scale-info = { workspace = true, features = ["derive"] }


frame-system.workspace = true
frame-support.workspace = true
pallet-balances.workspace = true
sp-std.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-io.workspace = true
pallet-funding.workspace = true
xcm.workspace = true
xcm-emulator.workspace = true
xcm-executor.workspace = true
xcm-builder.workspace = true
pallet-xcm.workspace = true
pallet-assets.workspace = true
polkadot-core-primitives.workspace = true
polkadot-runtime-parachains.workspace = true
polkadot-parachain.workspace = true

cumulus-primitives-core.workspace = true
cumulus-pallet-xcm.workspace = true
cumulus-pallet-xcmp-queue.workspace = true

parachain-info.workspace = true
parachains-common.workspace = true
sc-consensus-grandpa.workspace = true
pallet-im-online.workspace = true
polkadot-primitives.workspace = true
polkadot-service.workspace = true
sp-authority-discovery.workspace = true
sp-consensus-babe.workspace = true
polkadot-runtime-constants.workspace = true
pallet-staking.workspace = true
pallet-message-queue.workspace = true
pallet-membership.workspace = true
orml-oracle.workspace = true

# Runtimes
polkadot-runtime.workspace = true
statemint-runtime.workspace = true
polimec-parachain-runtime.workspace = true
penpal-runtime = { path = "./penpal", default-features = false }

[features]
default = [ "std" ]

std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"penpal-runtime/std",
	"polimec-parachain-runtime/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain/std",
	"polkadot-runtime-parachains/std",
	"polkadot-runtime/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"statemint-runtime/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"pallet-membership/std",
	"orml-oracle/std",
	"cumulus-pallet-xcmp-queue/std",
	"pallet-funding/std",
	"pallet-im-online/std",
	"pallet-message-queue/std",
	"pallet-staking/std",
	"parachains-common/std",
	"polkadot-primitives/std",
	"polkadot-runtime-constants/std",
	"sp-authority-discovery/std",
	"sp-consensus-babe/std"
]

runtime-benchmarks = [
	"statemint-runtime/runtime-benchmarks",
	"penpal-runtime/runtime-benchmarks",
	"polimec-parachain-runtime/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-funding/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-parachain/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks"
]
testing-node = [
	"pallet-funding/testing-node",
	"polimec-parachain-runtime/testing-node"
]
