[package]
name = "xcm-simulator-example"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Examples of xcm-simulator usage."
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.1" }
scale-info = { version = "2.3.1", features = ["derive"] }

frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32" }

xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.32" }
xcm-simulator = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.32" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.32" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.32" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.32" }
polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.32" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.32" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.32" }

parachain-info = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.32" }
statemint-runtime = { git = 'https://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.32' }
# Local

polimec-parachain-runtime = { path = "../runtimes/testnet" }
