[relaychain]
default_command = "polkadot"
default_args = ["-lparachain=debug"]

chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"
	ws_port = 9900
	validator = true

	[[relaychain.nodes]]
	name = "bob"
	validator = true

	[[relaychain.nodes]]
	name = "charlie"
	validator = true

	[[relaychain.nodes]]
	name = "dave"
	validator = true

[[parachains]]
id = 1000
cumulus_based = true
chain = "statemine-local"

    [parachains.collator]
    name = "statemine-collator"
    validator = true
    command = "polkadot-parachain"
    args = ["--force-authoring"]

[[parachains]]
id = 2000
cumulus_based = true

	[[parachains.collators]]
	name = "collator1"
	ws_port = 9910
	command = "polimec"
	args = [ "--alice" ]

	[[parachains.collators]]
	name = "collator2"
	command = "polimec"
	args = [ "--bob" ]


[[parachains]]
id = 2001
cumulus_based = true

	[[parachains.collators]]
	name = "collator3"
	ws_port = 9920
	command = "polimec"

	[[parachains.collators]]
	name = "collator4"
	command = "polimec"

[[hrmpChannels]]
sender = 2000
recipient = 1000
maxCapacity = 8
maxMessageSize = 8192

[[hrmpChannels]]
sender = 2000
recipient = 2001
maxCapacity = 8
maxMessageSize = 8192

[[hrmpChannels]]
sender = 2001
recipient = 2000
maxCapacity = 8
maxMessageSize = 8192

[[hrmpChannels]]
sender = 2001
recipient = 1000
maxCapacity = 8
maxMessageSize = 8192

[[hrmpChannels]]
sender = 1000
recipient = 2000
maxCapacity = 8
maxMessageSize = 8192

[[hrmpChannels]]
sender = 1000
recipient = 2001
maxCapacity = 8
maxMessageSize = 8192
