[package]
name = "polimec-shell-runtime"
description = "Shell runtime for Polimec on Polkadot."
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[build-dependencies]
substrate-wasm-builder.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", workspace = true, features = [
	"derive",
] }
scale-info = { workspace = true, features = ["derive"] }

# Substrate
frame-executive.workspace = true
frame-support.workspace = true
frame-system.workspace = true
# frame-try-runtime = { workspace = true, optional = true}
sp-api.workspace = true
sp-block-builder.workspace = true
sp-core.workspace = true
sp-inherents.workspace = true
sp-offchain.workspace = true
sp-runtime.workspace = true
sp-session.workspace = true
sp-std.workspace = true
sp-transaction-pool.workspace = true
sp-version.workspace = true
pallet-sudo.workspace = true

# Polkadot
xcm.workspace = true
xcm-builder.workspace = true
xcm-executor.workspace = true

# Cumulus
cumulus-pallet-parachain-system.workspace = true
cumulus-pallet-xcm.workspace = true
cumulus-primitives-core.workspace = true
parachain-info.workspace = true
parachains-common.workspace = true


[features]
default = [ "std" ]
std = [
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"parachain-info/std",
	"parachains-common/std",
	"pallet-sudo/std",
]
try-runtime = [
	"frame-executive/try-runtime",
	# "frame-try-runtime/try-runtime",
]