[package]
name = "polimec-xcm-executor"
description = "An abstract and configurable XCM message executor."
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
environmental = { version = "1.1.4", default-features = false }
parity-scale-codec = { workspace = true, default-features = false, features = ["derive"] }
xcm.workspace = true
sp-std.workspace = true
sp-io.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-weights.workspace = true
frame-support.workspace = true
log.workspace = true
frame-benchmarking = { workspace = true, optional = true}
xcm-executor.workspace = true


[features]
default = [ "std" ]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
std = [
	"environmental/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"log/std",
	"parity-scale-codec/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-weights/std",
	"xcm-executor/std",
	"xcm/std",
]
try-runtime = [ "frame-support/try-runtime", "sp-runtime/try-runtime" ]
