[package]
name = "polimec-xcm-executor"
description = "An abstract and configurable XCM message executor."
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
impl-trait-for-tuples = "0.2.2"
environmental = { version = "1.1.4", default-features = false }
parity-scale-codec = { version = "3.4.0", default-features = false, features = ["derive"] }
xcm.workspace = true
sp-std.workspace = true
sp-io.workspace = true
sp-arithmetic.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-weights.workspace = true
frame-support.workspace = true
log.workspace = true
frame-benchmarking = { workspace = true, optional = true}
xcm-executor.workspace = true


[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks"
]
std = [
	"parity-scale-codec/std",
	"xcm/std",
	"sp-std/std",
	"sp-io/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-weights/std",
	"frame-support/std",
	"log/std",
	"frame-benchmarking?/std",
	"xcm-executor/std",
	"environmental/std"
]
