[package]
name = 'polimec-common'
description = 'Common types, traits, and impls for Polimec and Projects'
authors = ['Polimec Foundation <info@polimec.org>']
documentation = "https://wiki.polimec.org/"
edition = "2021"
homepage = "https://www.polimec.org/"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Polimec/polimec-node"
version.workspace = true

[lints]
workspace = true

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
jwt-compact = { workspace = true, features = ["ed25519-dalek"] }
variant_count = "1.1.0"

frame-benchmarking = { workspace = true, optional = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-timestamp.workspace = true
sp-runtime.workspace = true
xcm.workspace = true
hex-literal.workspace = true
[features]
default = [ "std" ]
std = [
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"jwt-compact/std",
	"pallet-timestamp/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde/std",
	"sp-runtime/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
]
