name: Check Set-Up & Build

# Controls when the action will run.
on:
  pull_request:
    branches: [main]
    types: [synchronize, reopened, ready_for_review, labeled]
  label:
    types: [created, deleted]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RUSTFLAGS: "" # To ovveride the default "-D warnings" that can be too tedious.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fmt:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    container:
      image: paritytech/ci-linux:production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Fail fast: check formatting first as it doesn't require compilation
      - name: Check the formatting
        run: cargo +nightly fmt --all --check

  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    container:
      image: paritytech/ci-linux:production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Required by actions/cache@v3
      - name: Set-Up
        run: apt update && apt install -y nodejs

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # This will essentially compile the package without performing the final step of code generation.
      - name: Check the building
        run: SKIP_WASM_BUILD=1 cargo check --locked -p polimec-parachain-runtime

      

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    container:
      image: paritytech/ci-linux:production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Required by actions/cache@v3
      - name: Set-Up
        run: apt update && apt install -y nodejs

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test the Parachain
        run: SKIP_WASM_BUILD=1 cargo test --locked