name: Check Set-Up & Build

# Controls when the action will run.
on:
  pull_request:
    branches: [ main ]
    types: [ready_for_review, labeled]
  label:
    types: [created, deleted]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    env:
      NIGHTLY: nightly-2023-02-26 # Fix version to prevent cache misses with nightly changes

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set-Up
        run: sudo apt update && sudo apt install -y protobuf-compiler clang

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ env.NIGHTLY }}
          target: wasm32-unknown-unknown
          components: rustfmt

      # Fail fast: check formatting first as it doesn't require compilation
      - name: Check formatting
        run: cargo fmt --all --check

      - name: Cache Build artefacts
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check Build Parachain Runtime
        run: |
          SKIP_WASM_BUILD=1 cargo check --release -p polimec-parachain-runtime

      # TODO: Add Tests and Benchmarking