name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  Fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install nightly toolchain
      run: rustup toolchain install nightly-2023-12-01-x86_64-unknown-linux-gnu
    - name: fmt check
      run: cargo +nightly-2023-12-01 fmt --all --check

  # Release-Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Run sccache-cache
  #     uses: mozilla-actions/sccache-action@v0.0.3
  #   - name: Install protobuf
  #     run: sudo apt-get install protobuf-compiler
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     run: cargo build --release --verbose
  
  # Pallet-Tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Run sccache-cache
  #     uses: mozilla-actions/sccache-action@v0.0.3
  #   - name: Install protobuf
  #     run: sudo apt-get install protobuf-compiler

  #   - uses: actions/checkout@v4
  #   - name: Run Pallet Tests
  #     run: cargo test --features runtime-benchmarks --verbose

  # Integration-Tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Run sccache-cache
  #     uses: mozilla-actions/sccache-action@v0.0.3
  #   - name: Install protobuf
  #     run: sudo apt-get install protobuf-compiler
  #   - uses: actions/checkout@v4
  #   - name: STD Build
  #     run: cargo build --release --features std,instant-node
  #   - name: Run Integration Tests
  #     run: cargo test -p integration-tests
