name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run Pallet Tests
      run: cargo test --features runtime-benchmarks --verbose
    - name: Run Integration Tests
      run: cargo test -p integration-tests
